image: node:12.19.0

pipelines:
  default:
    - parallel:
        - step:
            name: Vulnerability Check
            caches:
              - node
            script:
              - /bin/bash ./scripts/pipeline.sh