deployment:
  image:
    repository: 002665144501.dkr.ecr.eu-central-1.amazonaws.com/bf-web-dev-initiation-bridgefund-portal
  env:
    ENVIRONMENT: dev
hostName: bridgefund-portal.bridgefund-development.net
