export const CLEAR_CUSTOMER = 'CLEAR_CUSTOMER';
export const SET_CUSTOMER = 'SET_CUSTOMER';
export const GET_CUSTOMER_LIST = 'GET_CUSTOMER_LIST';
export const SET_CUSTOMER_SUCCESS_MANAGERS = 'SET_CUSTOMER_SUCCESS_MANAGERS';
export const SET_SELECTED_CUSTOMER_ID = 'SET_SELECTED_CUSTOMER_ID';