export const GET_SNAPSHOT_LIST = "GET_SNAPSHOT_LIST";
export const HANDLE_SNAPSHOT_DIALOG_SHOWING = "HANDLE_SNAPSHOT_DIALOG_SHOWING";
export const HANDLE_SNAPSHOT_DIALOG_LOADING = "HANDLE_SNAPSHOT_DIALOG_LOADING";
