export const CLEAR_PERSON_STAKEHOLDER = "CLEAR_PERSON_STAKEHOLDER";
export const SET_PERSON_STAKEHOLDER = "SET_PERSON_STAKEHOLDER";

export const SET_STAKEHOLDER = "SET_STAKEHOLDER";
export const CLEAR_STAKEHOLDER = "CLEAR_STAKEHOLDER";

export const ADD_OR_UPDATE_STAKEHOLDER_LIST = "ADD_OR_UPDATE_STAKEHOLDER_LIST";
export const ADD_STAKEHOLDER_LIST = "ADD_STAKEHOLDER_LIST";
