const tabNames = {
	MY_TASKS_LIST: 'MY_TASKS_LIST',
	STATUS_OVERVIEW: 'STATUS_OVERVIEW',
	CUSTOMER_OVERVIEW: 'CUSTOMER_OVERVIEW',
	MANAGEMENT_INFO: 'MANAGEMENT_INFO',
};

module.exports = {
	tabNames
};