
export const GET_CUSTOMER = "GET_CUSTOMER";
export const CLEAR_CUSTOMER = "CLEAR_CUSTOMER";
export const CLEAR_SME_LOAN_REQUESTS = "CLEAR_SME_LOAN_REQUESTS";
export const GET_SME_LOAN_REQUESTS = "GET_SME_LOAN_REQUESTS";
export const GET_SME_LOAN_REQUEST_DETAILS = "GET_SME_LOAN_REQUEST_DETAILS";
export const CLEAR_SME_LOAN_REQUEST_DETAILS = "CLEAR_SME_LOAN_REQUEST_DETAILS";
export const GET_PRICING_PARAMETER = "GET_PRICING_PARAMETER";
export const CLEAR_PRICING_PARAMETER = "CLEAR_PRICING_PARAMETER";
export const GET_BANK_ACCOUNTS = "GET_BANK_ACCOUNTS";
export const CLEAR_BANK_ACCOUNTS = "CLEAR_BANK_ACCOUNTS";
export const SET_TRANSACTIONS_FOR_CATEGORIES = "SET_TRANSACTIONS_FOR_CATEGORIES";
export const SET_REQUEST_BLOCKS_GLOBALLY = "SET_REQUEST_BLOCKS_GLOBALLY";
export const SET_TRANSACTIONS_FOR_INTERNAL_TYPES = "SET_TRANSACTIONS_FOR_INTERNAL_TYPES";
export const CLEAR_TRANSACTIONS_FOR_INTERNAL_TYPES = "CLEAR_TRANSACTIONS_FOR_INTERNAL_TYPES";
export const SET_TAB_NAME_FOR_CHART = "SET_TAB_NAME_FOR_CHART";