export const GET_DEBT_FORM_DATA = "GET_DEBT_FORM_DATA";
export const CLEAR_DEBT_FORM_DATA = "CLEAR_GET_DEBT_FORM_DATA";

export const UPDATE_DEBT_AT_THIRD_PARTY = "UPDATE_DEBT_AT_THIRD_PARTY";
export const CLEAR_DEBT_AT_THIRD_PARTY = "CLEAR_DEBT_AT_THIRD_PARTY";

export const UPDATE_DEBITOR_CREDITOR = "UPDATE_DEBITOR_CREDITOR";
export const CLEAR_DEBITOR_CREDITOR = "CLEAR_DEBITOR_CREDITOR";

export const IMPORT_REQUEST_ID = "IMPORT_REQUEST_ID";