export const GET_CONTRACT_ID = "GET_CONTRACT_ID";
export const GET_LOAN_REQUEST_LIST = "GET_LOAN_REQUEST_LIST";
export const PROCESS_LOAN_REQUEST = "PROCESS_LOAN_REQUEST";
export const CLEAR_LOAN_REQUEST = "CLEAR_LOAN_REQUEST";
