export const GET_ALL_SNAPSHOTS = 'GET_ALL_SNAPSHOTS';
export const SHOW_DATABASE_SNAPSHOTS_DIALOG = 'SHOW_DATABASE_SNAPSHOTS_DIALOG';
export const CLOSE_DATABASE_SNAPSHOTS_DIALOG = 'CLOSE_DATABASE_SNAPSHOTS_DIALOG';
export const CREATE_SNAPSHOT_STARTED = 'CREATE_SNAPSHOT_STARTED';
export const RESTORE_SNAPSHOT_STARTED = 'RESTORE_SNAPSHOT_STARTED';
export const CREATE_SNAPSHOT_COMPLETED = 'CREATE_SNAPSHOT_COMPLETED';
export const RESTORE_SNAPSHOT_COMPLETED = 'RESTORE_SNAPSHOT_COMPLETED';