export const SET_FLEX_LOAN_OVERVIEW_DATA = "SET_FLEX_LOAN_OVERVIEW_DATA";
export const CLEAR_FLEX_LOAN_OVERVIEW_DATA = "CLEAR_FLEX_LOAN_OVERVIEW_DATA";
export const SET_FLEX_LOAN_WITHDRAWALS = "SET_FLEX_LOAN_WITHDRAWALS";
export const CLEAR_FLEX_LOAN_WITHDRAWALS = "CLEAR_FLEX_LOAN_WITHDRAWALS";
export const SET_ALL_FLEX_LOANS = "SET_ALL_FLEX_LOANS";
export const SET_INVERS_CONSENTS_FOR_SME = "SET_INVERS_CONSENTS_FOR_SME";