export const SET_LM_CUTOMER_SYS_ID = "SET_LM_CUTOMER_SYS_ID";
export const SET_LM_CONTRACT_SYS_ID = "SET_LM_CONTRACT_SYS_ID";
export const SET_LM_CONTRACT_TYPE = "SET_LM_CONTRACT_TYPE";
export const SET_LM_CONTRACT_MONGO_ID = "SET_LM_CONTRACT_MONGO_ID";
export const SET_IMPORTED_LOAN_REQUST_CONTRACT_ID = "SET_IMPORTED_LOAN_REQUST_CONTRACT_ID";
export const SET_FULL_AMOUNT_OF_DATA = "SET_FULL_AMOUNT_OF_DATA";