export const SAVE_SME_EMAILS = "SAVE_SME_EMAILS";
export const CLEAR_SME_EMAILS = "CLEAR_SME_EMAILS";
export const SAVE_NOTIFICATIONS = "SAVE_NOTIFICATIONS";
export const CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
export const UPDATE_NOTIFICATIONS = "UPDATE_NOTIFICATIONS";
export const SET_SEARCHED_QUERY_FOR_MESSAGES_LIST = "SET_SEARCHED_QUERY_FOR_MESSAGES_LIST";
export const SET_PAGINATION_FOR_MESSAGES_LIST = "SET_PAGINATION_FOR_MESSAGES_LIST";
export const SET_MESSAGES_LIST = "SET_MESSAGES_LIST";
export const CLEAR_MESSAGES_LIST_STATES = "CLEAR_MESSAGES_LIST_STATES";
export const HANDLE_LOADING_MESSAGES_LIST = "HANDLE_LOADING_MESSAGES_LIST";

// Admin Dashboard Notifications
export const SET_SEARCHED_QUERY_FOR_ADMIN_MESSAGES_LIST = "SET_SEARCHED_QUERY_FOR_ADMIN_MESSAGES_LIST";
export const SET_PAGINATION_FOR_ADMIN_MESSAGES_LIST = "SET_PAGINATION_FOR_ADMIN_MESSAGES_LIST";
export const SET_ADMIN_MESSAGES_LIST = "SET_ADMIN_MESSAGES_LIST";
export const CLEAR_ADMIN_MESSAGES_LIST_STATES = "CLEAR_ADMIN_MESSAGES_LIST_STATES";
export const HANDLE_LOADING_ADMIN_MESSAGES_LIST = "HANDLE_LOADING_ADMIN_MESSAGES_LIST";
