// export const PROCESS_PAYMENT = 'PROCESS_PAYMENT';
// export const PROCESS_HOLIDAYS = 'PROCESS_HOLIDAYS';
// export const ADD_NEW_TRANSACTION = 'ADD_NEW_TRANSACTION';
// export const ADD_NEW_TRANSACTION_ERROR = 'ADD_NEW_TRANSACTION_ERROR';
// export const CLEAR_TRANSACTION_ERROR = 'CLEAR_TRANSACTION_ERROR';

export const PAYMENTS_AS_AT_DATE = 'PAYMENTS_AS_AT_DATE'
