export const PROVISION_PARAMETERS = 'PROVISION_PARAMETERS';
export const PROVISION_PARAMETER_HISTORY = 'PROVISION_PARAMETER_HISTORY';
export const CREATE_PROVISION_PARAMETERS = 'CREATE_PROVISION_PARAMETERS';