export const PROCESS_PROVISION_DETAILS = 'PROCESS_PROVISION_DETAILS';
export const UPDATE_LENDED_AMOUNT = 'UPDATE_LANDED_AMOUNT';
export const PROCESS_DEFAULT_PROVISION_DETAILS = "PROCESS_DEFAULT_PROVISION_DETAILS";