export const PROCESS_SMELOANHISTORY = 'PROCESS_SMELOANHISTORY';
export const CLEAR_SMELOANHISTORY = 'CLEAR_SMELOANHISTORY';
export const PROCESS_SME_LOAN_HISTORIES = 'PROCESS_SME_LOAN_HISTORIES';
export const CLEAR_SME_LOAN_HISTORIES = 'CLEAR_SME_LOAN_HISTORIES';