export const SET_LOAN_STOP_HISTORY_ORIGIN = 'SET_LOAN_STOP_HISTORY_ORIGIN';
export const PROCESS_LOAN_STOP_HISTORY_DATA = 'PROCESS_LOAN_STOP_HISTORY_DATA';
export const SWITCH_LOAN_STOP_HISTORY_IS_BUSY = 'SWITCH_LOAN_STOP_HISTORY_IS_BUSY';
export const SET_IS_ACTIVE_AVAILABLE_FOR_SME = 'SET_IS_ACTIVE_AVAILABLE_FOR_SME';
export const SHOW_TEMPORARY_LOAN_STOP = 'SHOW_TEMPORARY_LOAN_STOP';
export const CLEAR_SME_LOAN_TEMPORARY_LOAN_STOP_DATA = 'CLEAR_SME_LOAN_TEMPORARY_LOAN_STOP_DATA';
export const UPDATE_TEMPORARY_STOP = 'UPDATE_TEMPORARY_STOP';
export const ADD_TEMPORARY_LOAN_STOP = 'ADD_TEMPORARY_LOAN_STOP';
