export const PROCESS_SME_LOANS_BY_CUSTOMER = 'PROCESS_SME_LOANS_BY_CUSTOMER';
export const SELECT_LOAN = 'SELECT_LOAN';
export const CLEAR_SELECTED_LOAN = 'CLEAR_SELECTED_LOAN';
export const CLEAR_LOANS = 'CLEAR_LOANS';
export const FIND_AND_UPDATE_LOAN = 'FIND_AND_UPDATE_LOAN';
export const SAVE_NEW_SME_LOAN = 'SAVE_NEW_SME_LOAN';
export const SAVE_NEW_SME_LOAN_BUSY = 'SAVE_NEW_SME_LOAN_BUSY';
export const SHOW_TERMINATE_SME_LOAN_MODAL = 'SHOW_TERMINATE_SME_LOAN_MODAL';
export const GET_CALCULATED_DATA_OF_LOAN_TRANSACTIONS = 'GET_CALCULATED_DATA_OF_LOAN_TRANSACTIONS';
export const CLEAR_CALCULATED_DATA_OF_LOAN_TRANSACTIONS = "CLEAR_CALCULATED_DATA_OF_LOAN_TRANSACTIONS";
export const SHOW_CANCEL_SME_LOAN_MODAL = "SHOW_CANCEL_SME_LOAN_MODAL";

