export const PROCESS_SME_MANDATES_BY_CUSTOMER = 'PROCESS_SME_MANDATES_BY_CUSTOMER';
export const SAVE_NEW_MANDATE = 'SAVE_NEW_MANDATE';
export const CLEAR_SME_MANDATES = 'CLEAR_SME_MANDATES';
export const CLEAR_SME_MANDATES_BY_CUSTOMER = 'CLEAR_SME_MANDATES_BY_CUSTOMER';
export const UPDATE_SME_MANDATE = 'UPDATE_SME_MANDATE';
export const UPDATE_SME_MANDATE_STATUS = 'UPDATE_SME_MANDATE_STATUS';